# Generated by Django 4.2.16 on 2024-10-25 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_name", models.CharField(max_length=255)),
                ("event_date", models.DateField()),
                ("round_fought", models.IntegerField()),
                ("method", models.CharField(max_length=100)),
                ("result", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Fighter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nickname", models.CharField(blank=True, max_length=255, null=True)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("nationality", models.CharField(max_length=100)),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "reach",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("stance", models.CharField(blank=True, max_length=50, null=True)),
                ("team", models.CharField(blank=True, max_length=255, null=True)),
                ("wins", models.IntegerField(default=0)),
                ("losses", models.IntegerField(default=0)),
                ("draws", models.IntegerField(default=0)),
                ("no_contests", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="FighterStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strikes_landed", models.IntegerField(default=0)),
                ("strikes_attempted", models.IntegerField(default=0)),
                ("takedowns_landed", models.IntegerField(default=0)),
                ("takedowns_attempted", models.IntegerField(default=0)),
                ("submission_attempts", models.IntegerField(default=0)),
                ("knockdowns", models.IntegerField(default=0)),
                (
                    "control_time",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "fighter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="myapp.fighter",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="TodoItem",),
        migrations.AddField(
            model_name="bout",
            name="fighter_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bouts_as_fighter_1",
                to="myapp.fighter",
            ),
        ),
        migrations.AddField(
            model_name="bout",
            name="fighter_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bouts_as_fighter_2",
                to="myapp.fighter",
            ),
        ),
        migrations.AddField(
            model_name="bout",
            name="winner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="won_bouts",
                to="myapp.fighter",
            ),
        ),
    ]
