# Generated by Django 4.2.16 on 2024-11-25 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_fighter_height_alter_fighter_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bout",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
