# Generated by Django 5.1.2 on 2025-04-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bout_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='bout',
            name='fighter_1',
        ),
        migrations.RemoveField(
            model_name='bout',
            name='fighter_2',
        ),
        migrations.RemoveField(
            model_name='bout',
            name='method',
        ),
        migrations.RemoveField(
            model_name='bout',
            name='result',
        ),
        migrations.RemoveField(
            model_name='bout',
            name='winner',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='draws',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='reach',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='stance',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='fighter',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='fighter',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='sig_strikes_abs',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='sig_strikes_perMin',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='strike_def',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='strikes_accuracy',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='sub_avg',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='takedown_average_per15',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='takedown_defense',
        ),
        migrations.RemoveField(
            model_name='fighterstats',
            name='takedowns_accuracy',
        ),
    ]
